Email Address: **jnjami40@gmail.com**

In [1]:
# You must run this code and use that data set for all the questions
import numpy as np
import pandas as pd

np.random.seed(42)

ids = np.arange(1, 11)
ages = np.random.randint(18, 60, 10)
salaries = np.random.randint(30000, 90000, 10)
departments = np.array(["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Sales", "HR"])

DF = pd.DataFrame({
"id": ids,
"age": ages,
"salary": salaries,
"dept": departments
})

DF.to_csv("employees.csv", index=False)
print("Sample Data Created and Saved as employees.csv")


Sample Data Created and Saved as employees.csv


**Numpy Problem Solve**

Answer To The Q. No. 01

In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("employees.csv")
df


id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [4]:
age_arr = df['age'].values
salary_arr = df['salary'].values

print("Age Array:")
print(age_arr)
print("dtype:", age_arr.dtype)
print("ndim:", age_arr.ndim)
print("shape:", age_arr.shape)
print("size:", age_arr.size)
print("\nSalary Array:")


print(salary_arr)
print("dtype:", salary_arr.dtype)
print("ndim:", salary_arr.ndim)
print("shape:", salary_arr.shape)
print("size:", salary_arr.size)

Age Array:
[56 46 32 25 38 56 36 40 28 28]
dtype: int64
ndim: 1
shape: (10,)
size: 10

Salary Array:
[77191 74131 46023 71090 31685 30769 89735 86101 32433 35311]
dtype: int64
ndim: 1
shape: (10,)
size: 10


Answer To The Q. No. 2

In [6]:
highest_salary=np.max(salary_arr)
print("Highest Salary:",highest_salary)

lowest_salary=np.min(salary_arr)
print("Lowest Salary:",lowest_salary)

age_avg=np.mean(age_arr)
print("Average Age:",age_avg)

salary_avg=np.mean(salary_arr)
print("Average Salary:",salary_avg)

Highest Salary: 89735
Lowest Salary: 30769
Average Age: 38.5
Average Salary: 57446.9


Answer To The Q. No. 3

In [10]:
ages_grater_than_30 = age_arr[age_arr > 30]
print("Ages grater than 30:")
print(ages_grater_than_30)

number_age_grater_than_30 = len(ages_grater_than_30)
print("\nNumber of employees older than 30:", number_age_grater_than_30)

Ages grater than 30:
[56 46 32 38 56 36 40]

Number of employees older than 30: 7


Answer To The Q. No. 4

In [11]:
age_increase_5=age_arr+5
print("Age Increases 5 Years:",age_increase_5)

Age Increases 5 Years: [61 51 37 30 43 61 41 45 33 33]


Answer To The Q. No. 5

In [13]:
total_salary=np.sum(salary_arr)
print("Total Salary:",total_salary)

difference_between_salary=highest_salary-lowest_salary
print("Difference Between Highest And Lowest Salary:",difference_between_salary)

Total Salary: 574469
Difference Between Highest And Lowest Salary: 58966


**Pandas Problem Solve**

Answer To The Q. No. 6

In [14]:
df

id  age  salary     dept
0   1   56   77191       HR
1   2   46   74131       IT
2   3   32   46023  Finance
3   4   25   71090       IT
4   5   38   31685       HR
5   6   56   30769    Sales
6   7   36   89735  Finance
7   8   40   86101       IT
8   9   28   32433    Sales
9  10   28   35311       HR

In [16]:
df.head(5)

df.info()

df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      10 non-null     int64 
 1   age     10 non-null     int64 
 2   salary  10 non-null     int64 
 3   dept    10 non-null     object
dtypes: int64(3), object(1)
memory usage: 452.0+ bytes


id       age        salary
count  10.00000  10.00000     10.000000
mean    5.50000  38.50000  57446.900000
std     3.02765  11.16791  24357.262884
min     1.00000  25.00000  30769.000000
25%     3.25000  29.00000  33152.500000
50%     5.50000  37.00000  58556.500000
75%     7.75000  44.50000  76426.000000
max    10.00000  56.00000  89735.000000

Answer To The Q No. 7

In [27]:
df.loc[:,['id','age','salary'],]
df.loc[:,['id','age','salary'],].tail(3)

id  age  salary
7   8   40   86101
8   9   28   32433
9  10   28   35311

Answer To The Q. No. 8

In [29]:
IT_department=df[df['dept']=='IT']
print(IT_department)
print("\n Number of employee in IT Department",len(IT_department))

   id  age  salary dept
1   2   46   74131   IT
3   4   25   71090   IT
7   8   40   86101   IT

 Number of employee in IT Department 3


Answer To The Q. No. 9

In [34]:
df_sort=df.sort_values(['salary'],ascending=False)
df_sort.head(3)

id  age  salary     dept
6   7   36   89735  Finance
7   8   40   86101       IT
0   1   56   77191       HR

Answer To The Q. No. 10

In [38]:
df.loc[df['salary']>80000,'salary']=80000
df

new_df_avg_salary=df['salary'].mean()
print("New Average Salary:",new_df_avg_salary)

New Average Salary: 55863.3
